from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'SatelliteScene',
    'Detection',
    'Zone',
    'Alert',
    'Verification',
    'StreamEvent',
    'MunicipalTicket',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'SatelliteScene': {
        'detections': 'Detection',
    },
    'Detection': {
        'scene': 'SatelliteScene',
        'zone': 'Zone',
        'alerts': 'Alert',
        'verifications': 'Verification',
    },
    'Zone': {
        'detections': 'Detection',
    },
    'Alert': {
        'detection': 'Detection',
    },
    'Verification': {
        'detection': 'Detection',
    },
    'StreamEvent': {
    },
    'MunicipalTicket': {
    },
}

# fmt: on